### ISSUE TITLE
RN 0.59.x support 

### ISSUE THREAD

**Issue by heyman333** [srfaytkn/react-native-youtube-sdk#12]
I am using version 0.59.10 

Is it possible to build Android from this version?

**Comment by farad4y** [comment]
Yes, there is a project that we are working on using RN 0.59

Just make sure read this
[Android X NOTE](https://github.com/srfaytkn/react-native-youtube-sdk#note)

**Comment by heyman333** [comment]
@farad4y 
Thank you for quick relpy. 
I am using this thrid-partry lob https://github.com/droibit/react-native-custom-tabs
which does not support AndroidX.
Is there any way I can use it with this module?

**Comment by farad4y** [comment]
We encountered the same problem and updated all libraries manually.
@srfaytkn know how to solve your problem, at least can show what you need to do

Yegenim sana saliyorum 😇

**Comment by srfaytkn** [comment]
@heyman333  you must migrate the library manually. Check out https://developer.android.com/jetpack/androidx/migrate for migration guide

**Comment by heyman333** [comment]
@farad4y @srfaytkn 
I really appreciate your kindness.
Unfortunately, we have too many dependencies, and thought it would be hard to check all the third party modules right away ...

Anyway, I hope this library is known to a lot of people, and I will always try to use this library and contriburte if I have chance

thank you guys!
