### ISSUE TITLE
Execution failed for task ':app:processDebugResources'

### ISSUE THREAD

**Issue by longb1997** [srfaytkn/react-native-youtube-sdk#5]

**Comment by Cyberfolks** [comment]
to resolve this issue i have made some changes.
example removed and copy the file YouTubePlayer.js and paste it inside root folder.
and change the file path in index.js 
"example/libs/ YouTubePlayer" to "./YouTubePlayer".

2nd issue was mainSDK version of com.pierfrancescosoffritti.androidyoutubeplayer witch was lower then 17. so i make some changes in react-native-youtube-sdk\android\src\main\AndroidManifest.xml.

<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
  package="com.srfaytkn.reactnative"
+  xmlns:tools="http://schemas.android.com/tools">

  <uses-permission android:name="android.permission.INTERNET"/>
  <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
+ <uses-sdk tools:overrideLibrary="com.pierfrancescosoffritti.androidyoutubeplayer"/>

  <application>
    <activity
      android:name=".FullscreenPlayerActivity"
      android:screenOrientation="landscape"/>
  </application>
</manifest>

right now working perfectly on android. 

@farad4y  @srfaytkn please resolve the UIManager issue.

**Comment by farad4y** [comment]
Agzina sictimin adami 50 tane issue acma, sinirleniyorum.
@Cyberfolks If you do that, send pull request.

**Comment by Cyberfolks** [comment]
@farad4y ok
